export const sample_data = [
  {
    title: "asdfghjkl",
    items: [
      {
        Image: "https://picsum.photos/130/100",
        Title: "sedrftyghuijk",
        Price: 1000,
        OldPrice: 2000,
        Discount: (1000 / 2000) * 100,
        id: generateId(),
        quantity: 1,
      },
      {
        Image: "https://picsum.photos/130/100",
        Title: "sedrftyghuijk",
        Price: 1000,
        OldPrice: 2000,
        Discount: (1000 / 2000) * 100,
        id: generateId(),
        quantity: 1,
      },
      {
        Image: "https://picsum.photos/130/100",
        Title: "sedrftyghuijk",
        Price: 1000,
        OldPrice: 2000,
        Discount: (1000 / 2000) * 100,
        id: generateId(),
        quantity: 1,
      },
      {
        Image: "https://picsum.photos/130/100",
        Title: "sedrftyghuijk",
        Price: 1000,
        OldPrice: 2000,
        Discount: (1000 / 2000) * 100,
        id: generateId(),
        quantity: 1,
      },
    ],
    redirect: {
      label: "See more",
      url: "https://www.google.com/",
    },
  },
  {
    title: "asdfghjkl",
    items: [
      {
        Image: "https://picsum.photos/130/100",
        Title: "sedrftyghuijk",
        Price: 1000,
        OldPrice: 2000,
        Discount: (1000 / 2000) * 100,
        id: generateId(),
        quantity: 1,
      },
      {
        Image: "https://picsum.photos/130/100",
        Title: "sedrftyghuijk",
        Price: 1000,
        OldPrice: 2000,
        Discount: (1000 / 2000) * 100,
        id: generateId(),
        quantity: 1,
      },
      {
        Image: "https://picsum.photos/130/100",
        Title: "sedrftyghuijk",
        Price: 1000,
        OldPrice: 2000,
        Discount: (1000 / 2000) * 100,
        id: generateId(),
        quantity: 1,
      },
      {
        Image: "https://picsum.photos/130/100",
        Title: "sedrftyghuijk",
        Price: 1000,
        OldPrice: 2000,
        Discount: (1000 / 2000) * 100,
        id: generateId(),
        quantity: 1,
      },
    ],
    redirect: {
      label: "See more",
      url: "https://www.google.com/",
    },
  },
  {
    title: "asdfghjkl",
    items: [
      {
        Image: "https://picsum.photos/130/100",
        Title: "sedrftyghuijk",
        Price: 1000,
        OldPrice: 2000,
        Discount: (1000 / 2000) * 100,
        id: generateId(),
        quantity: 1,
      },
      {
        Image: "https://picsum.photos/130/100",
        Title: "sedrftyghuijk",
        Price: 1000,
        OldPrice: 2000,
        Discount: (1000 / 2000) * 100,
        id: generateId(),
        quantity: 1,
      },
      {
        Image: "https://picsum.photos/130/100",
        Title: "sedrftyghuijk",
        Price: 1000,
        OldPrice: 2000,
        Discount: (1000 / 2000) * 100,
        id: generateId(),
        quantity: 1,
      },
      {
        Image: "https://picsum.photos/130/100",
        Title: "sedrftyghuijk",
        Price: 1000,
        OldPrice: 2000,
        Discount: (1000 / 2000) * 100,
        id: generateId(),
        quantity: 1,
      },
    ],
    redirect: {
      label: "See more",
      url: "https://www.google.com/",
    },
  },

  {
    title: "asdfghjkl",
    items: [
      {
        Image: "https://picsum.photos/130/100",
        Title: "sedrftyghuijk",
        Price: 1000,
        OldPrice: 2000,
        Discount: (1000 / 2000) * 100,
        id: generateId(),
        quantity: 1,
      },
      {
        Image: "https://picsum.photos/130/100",
        Title: "sedrftyghuijk",
        Price: 1000,
        OldPrice: 2000,
        Discount: (1000 / 2000) * 100,
        id: generateId(),
        quantity: 1,
      },
      {
        Image: "https://picsum.photos/130/100",
        Title: "sedrftyghuijk",
        Price: 1000,
        OldPrice: 2000,
        Discount: (1000 / 2000) * 100,
        id: generateId(),
        quantity: 1,
      },
      {
        Image: "https://picsum.photos/130/100",
        Title: "sedrftyghuijk",
        Price: 1000,
        OldPrice: 2000,
        Discount: (1000 / 2000) * 100,
        id: generateId(),
        quantity: 1,
      },
    ],
    redirect: {
      label: "See more",
      url: "https://www.google.com/",
    },
  },
  {
    title: "asdfghjkl",
    items: [
      {
        Image: "https://picsum.photos/130/100",
        Title: "sedrftyghuijk",
        Price: 1000,
        OldPrice: 2000,
        Discount: (1000 / 2000) * 100,
        id: generateId(),
        quantity: 1,
      },
      {
        Image: "https://picsum.photos/130/100",
        Title: "sedrftyghuijk",
        Price: 1000,
        OldPrice: 2000,
        Discount: (1000 / 2000) * 100,
        id: generateId(),
        quantity: 1,
      },
      {
        Image: "https://picsum.photos/130/100",
        Title: "sedrftyghuijk",
        Price: 1000,
        OldPrice: 2000,
        Discount: (1000 / 2000) * 100,
        id: generateId(),
        quantity: 1,
      },
      {
        Image: "https://picsum.photos/130/100",
        Title: "sedrftyghuijk",
        Price: 1000,
        OldPrice: 2000,
        Discount: (1000 / 2000) * 100,
        id: generateId(),
        quantity: 1,
      },
    ],
    redirect: {
      label: "See more",
      url: "https://www.google.com/",
    },
  },
  {
    title: "asdfghjkl",
    items: [
      {
        Image: "https://picsum.photos/130/100",
        Title: "sedrftyghuijk",
        Price: 1000,
        OldPrice: 2000,
        Discount: (1000 / 2000) * 100,
        id: generateId(),
        quantity: 1,
      },
      {
        Image: "https://picsum.photos/130/100",
        Title: "sedrftyghuijk",
        Price: 1000,
        OldPrice: 2000,
        Discount: (1000 / 2000) * 100,
        id: generateId(),
        quantity: 1,
      },
      {
        Image: "https://picsum.photos/130/100",
        Title: "sedrftyghuijk",
        Price: 1000,
        OldPrice: 2000,
        Discount: (1000 / 2000) * 100,
        id: generateId(),
        quantity: 1,
      },
      {
        Image: "https://picsum.photos/130/100",
        Title: "sedrftyghuijk",
        Price: 1000,
        OldPrice: 2000,
        Discount: (1000 / 2000) * 100,
        id: generateId(),
        quantity: 1,
      },
    ],
    redirect: {
      label: "See more",
      url: "https://www.google.com/",
    },
  },
  {
    title: "asdfghjkl",
    items: [
      {
        Image: "https://picsum.photos/130/100",
        Title: "sedrftyghuijk",
        Price: 1000,
        OldPrice: 2000,
        Discount: (1000 / 2000) * 100,
        id: generateId(),
        quantity: 1,
      },
      {
        Image: "https://picsum.photos/130/100",
        Title: "sedrftyghuijk",
        Price: 1000,
        OldPrice: 2000,
        Discount: (1000 / 2000) * 100,
        id: generateId(),
        quantity: 1,
      },
      {
        Image: "https://picsum.photos/130/100",
        Title: "sedrftyghuijk",
        Price: 1000,
        OldPrice: 2000,
        Discount: (1000 / 2000) * 100,
        id: generateId(),
        quantity: 1,
      },
      {
        Image: "https://picsum.photos/130/100",
        Title: "sedrftyghuijk",
        Price: 1000,
        OldPrice: 2000,
        Discount: (1000 / 2000) * 100,
        id: generateId(),
        quantity: 1,
      },
    ],
    redirect: {
      label: "See more",
      url: "https://www.google.com/",
    },
  },

  {
    title: "asdfghjkl",
    items: [
      {
        Image: "https://picsum.photos/130/100",
        Title: "sedrftyghuijk",
        Price: 1000,
        OldPrice: 2000,
        Discount: (1000 / 2000) * 100,
        id: generateId(),
        quantity: 1,
      },
      {
        Image: "https://picsum.photos/130/100",
        Title: "sedrftyghuijk",
        Price: 1000,
        OldPrice: 2000,
        Discount: (1000 / 2000) * 100,
        id: generateId(),
        quantity: 1,
      },
      {
        Image: "https://picsum.photos/130/100",
        Title: "sedrftyghuijk",
        Price: 1000,
        OldPrice: 2000,
        Discount: (1000 / 2000) * 100,
        id: generateId(),
        quantity: 1,
      },
      {
        Image: "https://picsum.photos/130/100",
        Title: "sedrftyghuijk",
        Price: 1000,
        OldPrice: 2000,
        Discount: (1000 / 2000) * 100,
        id: generateId(),
        quantity: 1,
      },
    ],
    redirect: {
      label: "See more",
      url: "https://www.google.com/",
    },
  },
];

export const list_items = [
  "Fresh",
  "Best Sellers",
  "Today's Deals",
  "Mobiles",
  "Electronics",
  "Home & Kitchen",
  "Customer Service",
  "Prime",
  "Amazon Pay",
  "New Releases",
  "Fashion",
  "Car & Motorbike",
  "Computers",
  "Sports, Fitness & Outdoors",
  "Books",
  "Home Improvement",
  "Toys & Games",
  "Beauty & Personal Care",
  "Gift Cards",
  "Grocery & Gourmet Foods",
  "Baby",
  "Health, Household & Personal Care",
  "Custom Products",
  "Gift Ideas",
  "Video Gam",
];

export const sidebarData = [
  {
    title: "Trending",
    items: [
      { heading: "Best Sellers", arrow: false },
      { heading: "New Releases", arrow: false },
      { heading: "Movers and Shakers", arrow: false },
    ],
  },
  {
    title: "Digital Content and Devices",
    items: [
      { heading: "Echo & Alexa", arrow: true },
      { heading: "Fire TV", arrow: true },
      { heading: "Kindle E-Readers & eBooks", arrow: true },
      { heading: "Audible Audiobooks", arrow: true },
      { heading: "Amazon Prime Video", arrow: true },
      { heading: "Amazon Prime Music", arrow: true },
    ],
  },
  {
    title: "Shop by Category",
    items: [
      { heading: "Mobiles, Computers", arrow: true },
      { heading: "TV, Appliances, Electronics", arrow: true },
      { heading: "Men's Fashion", arrow: true },
      { heading: "Women's Fashion", arrow: true },
      { heading: "See all", arrow: true },
    ],
  },
  {
    title: "Programs & Features",
    items: [
      { heading: "Amazon Pay", arrow: false },
      { heading: "Gift Cards & Mobile Recharges", arrow: true },
      { heading: "Amazon Launchpad", arrow: false },
      { heading: "Amazon Business", arrow: false },
      { heading: "See all", arrow: false },
    ],
  },
  {
    title: "Help & Settings",
    items: [
      { heading: "Your Account", arrow: false },
      { heading: "Customer Service", arrow: false },
      { heading: "Sign in", arrow: false },
    ],
  },
];

function generateId() {
  return Math.random().toString(36).substring(2, 9);
}
